### ISSUE TITLE
Normalize Names on Increment and Decrement Operations

### ISSUE THREAD

**Issue by subecho** [subecho/KarmaChameleon#5]
Currently, Karma Chameleon treats the following messages as discrete entries:
`#topic++`
`topic++`
`@topic++`
When the `@topic` is **not** a username. This causes three separate karma entities to exist each with its own score. We should try to "normalize" these so that all three of the previous messages will refer to the same entity.

**Comment by ddupuisfl** [comment]
@subecho++
