### ISSUE TITLE
Add Logging for the Event Manager Class

### ISSUE THREAD

**Issue by subecho** [subecho/KarmaChameleon#9]
Currently there is no logging in the Event Manager class. We should add some logging for information about messages coming in (like event type).

**Comment by bdecato** [comment]
My exploration with leaderboard today made this more apparent as well: maybe we could have a logfile outside the main karma file that logs the details of each increment/decrement (maybe the date & time, day of week, user, incremented/decremented thing, and whether it was a plus or a minus).

With this kind of a log file, we could building some nice visualizations of usage by time and day of week, trending topics over time, and things like that.
